# Basic Data Exploration and Cleaning using Pandas

# 1. Importing required Libraries and Loading the Dataset

In [1]:
import pandas as pd

In [2]:
# Loading the csv dataset into pandas dataframe
df=pd.read_csv("C:\\Users\\home\\Documents\\Celebal Assignments\\Ecommerce_Dataset\\Combined_dataset.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

# 2. Data Exploration

### 2a. Displaying first and last few rows
##### Head -> Displays first 5 rows by default
##### Tail -> Displays last 5 rows by default

In [3]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
# Displaying first 10 rows using head
df.head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [6]:
# Displaying last 20 rows using tail
df.tail(20)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
980,18864968,Lavie,Glossy Sacy Women Pink Animal Textured Zip Aro...,4.4,21,1999,65.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""L""}]","[""rw-18864968_cae700""]",NaN,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",wallets
981,9029979,Hidesign,Men Brown Solid Leather Two Fold Wallet,4.4,8,2595,NaN,"""₹2,595.00""",INR,http://assets.myntassets.com/assets/images/902...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",wallets
982,16295388,LOUIS STITCH,Men Brown Leather Two Fold Wallet,4.4,10,4200,75.0,"""₹1,050.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Gun███al ███tch█████████E L█████████,"[{""size"":""Onesize""}]",NaN,"A-1███ Bl███ A,█████████Lok███████████████████...","[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wallets
983,16295382,LOUIS STITCH,Men Brown & Black Leather Two Fold Wallet,0.0,0,4200,75.0,"""₹1,050.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Gun███al ███tch█████████E L█████████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","A-1███ Bl███ A,█████████Lok███████████████████...","[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wallets
984,17956822,Fossil,Men Black Dial & Leather Straps Dayliner Analo...,3.9,7,9995,50.0,"""₹4,997.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]","[""rw-17956822_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
985,17981742,MVMT,Men Black Raptor Analogue Watch 28000152-D,4.5,11,20832,50.0,"""₹10,416.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""L""}]",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.0,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]",NaN,"Fla███o. ███, 6█████████y C███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
987,7349545,Fantasy World,Unisex Grey Digital Watch,3.7,119,499,20.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/734...,...,"{""1_star"":20,""2_stars"":8,""3_stars"":13,""4_stars...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-7349545_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
988,8076639,French Connection,Women Charcoal Grey Analogue Watch FC1317RGM,4.4,563,6250,60.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/807...,...,"{""1_star"":35,""2_stars"":21,""3_stars"":22,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8076639_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
989,21948792,Adwitiya Collection,Women Embellished Dial & Bracelet Style Straps...,4.1,7,9709,72.0,"""₹9,709.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
990,9053317,TIMESMITH,Men Black Analogue Watch TSC-008,3.7,304,2499,88.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/905...,...,"{""1_star"":54,""2_stars"":20,""3_stars"":34,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9053317_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",NaN,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Br ███erp███es,"[{""size"":""Onesize""}]",NaN,Kha███ no███122█████████lhi██████████████████,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

### 2b. Summarizing columns in the dataframe using df.describe()

In [7]:
df.describe() # gives statistical summary of all numerical columns

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [8]:
df.describe(include='str') # gives summary of categorical columns

,title,product_description,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,427,699,1000,219,699,438,1000,1000,1000
unique,454,989,466,1,1000,16,998,658,967,808,302,301,672,219,298,22,468,159,97
top,Roadster,Women Pink Solid Top,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Black and White printed knitte...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Blouse"",""specification...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on IndusI...",tops
freq,30,3,25,1000,1,650,2,16,4,114,27,40,135,1,40,126,306,265,122

In [9]:
df.describe(include='all') #gives summary of every column

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
count,1.000000e+03,1000,1000,1000.0000,1000.000000,1000.00000,879.000000,1000,1000,1000,...,1000,427,699,1000,219,699,438,1000,1000,1000
unique,NaN,454,989,NaN,NaN,NaN,NaN,466,1,1000,...,808,302,301,672,219,298,22,468,159,97
top,NaN,Roadster,Women Pink Solid Top,NaN,NaN,NaN,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on IndusI...",tops
freq,NaN,30,3,NaN,NaN,NaN,NaN,25,1000,1,...,114,27,40,135,1,40,126,306,265,122
mean,1.713437e+07,NaN,NaN,3.6215,76.691000,2723.24100,53.503982,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.813766e+06,NaN,NaN,1.3744,241.114263,2408.69736,18.029201,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,5.868460e+05,NaN,NaN,0.0000,0.000000,249.00000,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.511501e+07,NaN,NaN,3.7000,7.000000,1399.00000,44.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.820890e+07,NaN,NaN,4.1000,17.000000,1999.00000,56.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.902737e+07,NaN,NaN,4.3000,58.000000,3299.00000,66.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.274707e+07,NaN,NaN,5.0000,4441.000000,22199.00000,88.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2c. Structural summary of the dataframe using df.info()

In [10]:
# It tells about how many non-null values are there, as well as the data type of the columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

### 2d. Shape of the DataFrame

In [11]:
print('Shape of the DataFrame is: ',df.shape)
print('Number of rows in the DataFrame are: ',df.shape[0])
print('Number of columns in the DataFrame are: ',df.shape[1])

Shape of the DataFrame is:  (1000, 24)
Number of rows in the DataFrame are:  1000
Number of columns in the DataFrame are:  24

### 2e. Columns and Data Types

In [12]:
# df.columns returns an Index object containing all column names.
# We use a for loop to iterate through each column name one by one.
# A counter variable 'c' is used manually to display the column number.
print('Column Names')
print('------------')
c=0
for i in df.columns:
    c+=1
    print(c,i)

Column Names
------------
1 product_id
2 title
3 product_description
4 rating
5 ratings_count
6 initial_price
7 discount
8 final_price
9 currency
10 images
11 delivery_options
12 product_details
13 breadcrumbs
14 product_specifications
15 amount_of_stars
16 what_customers_said
17 seller_name
18 sizes
19 videos
20 seller_information
21 variations
22 best_offer
23 more_offers
24 category

In [13]:
# df.dtypes is used to know about the datatypes of all the columns in the dataframe
print('Data Types:')
df.dtypes

Data Types:

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

# 3. Handling Missing Values

### 3a. Identifying the missing values

In [14]:
# df.isnull() returns a DataFrame of True/False values — 
# True where value is missing, False where value is present.
print(df.isnull())
# .sum() then counts all the True values per column (since True = 1, False = 0)
print(df.isnull().sum())
# to print columns which only have missing values we do the following
print('\nColumns with missing values')
print('-----------------------------')
print(df.isnull().sum()[df.isnull().sum()>0])

     product_id  title  product_description  rating  ratings_count  \
0         False  False                False   False          False
1         False  False                False   False          False
2         False  False                False   False          False
3         False  False                False   False          False
4         False  False                False   False          False
..          ...    ...                  ...     ...            ...
995       False  False                False   False          False
996       False  False                False   False          False
997       False  False                False   False          False
998       False  False                False   False          False
999       False  False                False   False          False

     initial_price  discount  final_price  currency  images  ...  \
0            False     False        False     False   False  ...
1            False     False        False     False   False  ...
2            False     False        False     False   False  ...
3            False     False        False     False   False  ...
4            False     False        False     False   False  ...
..             ...       ...          ...       ...     ...  ...
995          False     False        False     False   False  ...
996          False     False        False     False   False  ...
997          False     False        False     False   False  ...
998          False     False        False     False   False  ...
999          False     False        False     False   False  ...

     amount_of_stars  what_customers_said  seller_name  sizes  videos  \
0              False                 True         True  False   False
1              False                 True         True  False   False
2              False                 True         True  False   False
3              False                 True         True  False   False
4              False                 True         True  False    True
..               ...                  ...          ...    ...     ...
995            False                 True         True  False   False
996            False                 True         True  False   False
997            False                 True         True  False    True
998            False                 True        False  False    True
999            False                 True         True  False    True

     seller_information  variations  best_offer  more_offers  category
0                  True       False       False        False     False
1                  True       False       False        False     False
2                  True       False       False        False     False
3                  True        True       False        False     False
4                  True       False       False        False     False
..                  ...         ...         ...          ...       ...
995                True        True       False        False     False
996                True        True       False        False     False
997                True       False       False        False     False
998               False        True       False        False     False
999                True       False       False        False     False

[1000 rows x 24 columns]
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

Columns with missing values
-----------------------------
discount               121
what_customers_said    573
seller_name            301
videos                 781
seller_information     301
variations             562
dtype: int64

### 3b. Fill/Drop Missing Values
##### We only drop missing values when the number of missing values is less
##### In this case as the number of missing values are more we will not drop them as the meaning of the dataframe might change
##### We can drop the missing values using the function df.dropna()
##### Hence we will fill the missing values with appropriate values

#### Strategy to fill missing values

##### 1. discount -> as its datatype is float, it should be filled with numerical values, hence we can use median to do so as the column might have outliers due to which mean might give wrong values
##### 2. what_customers_said -> its datatype is str, hence we can fill it using 'No reviews'
##### 3. seller_name -> its datatype is also str, hence we can fill it using 'Unknown seller'
##### 4. videos -> its datatype is also str, hence we can fill it using 'No videos'
##### 5. seller_information -> its datatype is also str, hence we can fill it using 'No information available'
##### 6. variations -> its datatype is also str, hence we can fill it using 'No variations'

In [15]:
df['discount'] = df['discount'].fillna(df['discount'].median())
df['what_customers_said'] = df['what_customers_said'].fillna('No reviews')
df['seller_name'] = df['seller_name'].fillna('Unknown seller')
df['videos'] = df['videos'].fillna('No videos')
df['seller_information'] = df['seller_information'].fillna('No information available')
df['variations'] = df['variations'].fillna('No variations')
# All the missing values have been filled
# To verify it:
print(df.isnull().sum())
print('\nMissing values after cleaning: ',df.isnull().sum().sum())
df # All missing values have been filled in the dataframe

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

Missing values after cleaning:  0

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",No information available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",No information available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No reviews,Unknown seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",No information available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",No information available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No videos,No information available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",No information available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",No information available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]",No videos,No information available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No reviews,Tru███m R███il,"[{""size"":""Onesize""}]",No videos,Sho███o. ███-10█████████enu███████████████████...,No variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No reviews,Unknown seller,"[{""size"":""Medium""}]",No videos,No information available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

# 4. Basic Operations - Filter & Select

### 4a. Rename

In [16]:
# Renaming the column what_customers_said to customer_reviews
df.rename(columns={"what_customers_said":"customer_reviews"},inplace=True)
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,customer_reviews,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",No information available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",No information available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No reviews,Unknown seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",No information available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",No information available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No videos,No information available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",No information available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",No information available,No variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No reviews,Unknown seller,"[{""size"":""Onesize""}]",No videos,No information available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No reviews,Tru███m R███il,"[{""size"":""Onesize""}]",No videos,Sho███o. ███-10█████████enu███████████████████...,No variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No reviews,Unknown seller,"[{""size"":""Medium""}]",No videos,No information available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

### 4b. Selecting specific columns
##### As the DataFrame has 24 columns, out of those we can select a few meaningful columns and work with them
##### We can select columns like : product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,seller_name,category

In [17]:
new_df = df[['product_id', 'title', 'product_description', 'rating', 'ratings_count', 
         'initial_price', 'discount', 'final_price', 'currency', 'delivery_options', 
         'product_details', 'seller_name', 'category']]
print(f"New shape: {new_df.shape}")
print(f"Selected columns: {list(new_df.columns)}")
new_df.head()

New shape: (1000, 13)
Selected columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'delivery_options', 'product_details', 'seller_name', 'category']

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,seller_name,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...",Unknown seller,backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...",Unknown seller,backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...",Unknown seller,backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...",Unknown seller,backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...",Unknown seller,bath-robe

### 4c. Filtering rows

In [18]:
# Filtering products with rating >= 4.0
high_rated = new_df[new_df['rating'] >= 4.0]
print('High-rated products (≥ 4.0): ',len(high_rated))

# Filtering products with discount > 50%
high_discount = new_df[new_df['discount'] > 50]
print('Products with >50% discount: ',len(high_discount))

# Filtering products with price under ₹1000
budget = new_df[new_df['initial_price'] < 1000]
print('Budget products (< ₹1000): ',len(budget))

# Filtering according to the best deals using both high rated and high discount
best_deals = new_df[(new_df['rating'] >= 4.0) & (new_df['discount'] > 50)]
print('Best deals (rated ≥4.0 + discount >50%): ',len(best_deals))
best_deals.head()

High-rated products (≥ 4.0):  615
Products with >50% discount:  644
Budget products (< ₹1000):  166
Best deals (rated ≥4.0 + discount >50%):  369

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,seller_name,category
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...",Unknown seller,backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...",Unknown seller,backpacks
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,56.0,"""₹1,399.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Soap dispenser in glazed stone...",H &███Hen███ & █████████eta█████████████████████,bathroom-accessories
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 Bath TowelFeatu...",Unknown seller,bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 king bedsheet w...",Unknown seller,bedsheets

In [19]:
new_df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,seller_name,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...",Unknown seller,backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...",Unknown seller,backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...",Unknown seller,backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...",Unknown seller,backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...",Unknown seller,bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Features:Nothing about the For...",Unknown seller,watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...",Unknown seller,watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Case style: Analogue watch, ha...",Unknown seller,watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watch D...",Tru███m R███il,watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: One yoga matColou...",Unknown seller,yoga-mats

### 4d. Dropping columns
##### Dropping the column final_price as the values are the same as initial_price,
##### meaning no discount has been applied, making it redundant

In [20]:
new_df = new_df.drop(columns=['final_price'])
print('New shape: ',new_df.shape)
new_df

New shape:  (1000, 12)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,currency,delivery_options,product_details,seller_name,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...",Unknown seller,backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...",Unknown seller,backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...",Unknown seller,backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...",Unknown seller,backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...",Unknown seller,bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Features:Nothing about the For...",Unknown seller,watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...",Unknown seller,watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Case style: Analogue watch, ha...",Unknown seller,watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watch D...",Tru███m R███il,watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: One yoga matColou...",Unknown seller,yoga-mats

# 5. Remove Duplicates

### 5a. Checking if duplicates exist

In [21]:
print('Number of duplicate rows: ', new_df.duplicated().sum())
print('Total rows before removing duplicates: ', len(new_df))

Number of duplicate rows:  0
Total rows before removing duplicates:  1000

### 5b. Removing duplicates
##### In this case there are no duplicates but if they exist then we use the following code to remove them

In [22]:
new_df = new_df.drop_duplicates()
print('Total rows after removing duplicates: ', len(new_df))

Total rows after removing duplicates:  1000

# 6. Derived Column Creation
##### Creating a derived column :    total_amount_to_be_paid=initial_price-(initial_price*(discount/100))

In [23]:
new_df['total_amount_to_be_paid'] = new_df['initial_price'] - (new_df['initial_price'] * (new_df['discount'] / 100))
# Verify if the derived column is created or not
print(new_df[['initial_price', 'discount', 'total_amount_to_be_paid']].head())

   initial_price  discount  total_amount_to_be_paid
0           3995      58.0                  1677.90
1           2899      35.0                  1884.35
2           2999      65.0                  1049.65
3           1675      52.0                   804.00
4           2899      17.0                  2406.17

# 7. Saving the cleaned dataset as a new CSV file

In [24]:
new_df.to_csv("C:\\Users\\home\\Documents\\Celebal Assignments\\new_Combined_dataset.csv", index=False)# dataset with column deletion
# Also saving the cleaned dataset with no column delection
df.to_csv("C:\\Users\\home\\Documents\\Celebal Assignments\\new_Cleaned_Combined_dataset.csv", index=False)#dataset without column deletion